---
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Install Docker prerequisites
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "gnupg2",
        "software-properties-common",
      ]
    update_cache: yes

- name: Add Docker APT repository
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_distribution|lower }}
      {{ docker_distribution if docker_distribution is defined else ansible_distribution_release }}
      stable

- name: Populate service facts
  service_facts:

- name: Install Docker without containerd
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
  when: 
    - ansible_facts.services["containerd"] is defined


- name: Install Docker with containerd
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
  when: 
    - ansible_facts.services["containerd"] is not defined
    - withoutContainerd is not defined

- name: Install Docker with containerd
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
  when: 
    - ansible_facts.services["containerd"] is not defined
    - withoutContainerd is defined

# - name: Download compose
#   get_url:
#     url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
#     dest: /usr/local/bin/docker-compose
#     mode: "0755"

- name: Ensures /etc/systemd/system/docker.service.d dir exists
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    recurse: yes

- name: set docker overrydes
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --dns 8.8.8.8 --dns 1.1.1.1 --containerd=/run/containerd/containerd.sock
      LimitMEMLOCK=infinity
    mode: "0644"
  notify:
    - restart docker service

- meta: flush_handlers